# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml peer_ai_review.py README.md ./

# Install uv and dependencies for all providers
RUN pip install --no-cache-dir uv && \
    pip install --no-cache-dir ".[all]"

# Expose nothing specific (stdio server)

# Default entrypoint
ENTRYPOINT ["uv", "run", "peer_ai_review.py"]
